### ISSUE TITLE
The output_buffer seems to lag one transaction behind the callback

### ISSUE THREAD

**Issue by DavidAntliff** [eriksl/usitwislave#10]
If the master invokes a read transaction on the slave, and the data callback populates the output_buffer with a value, that data does not reach the master until the _second_ read transaction.

For example:

```
static uint8_t data = 0;

static void data_callback(uint8_t input_buffer_length, const uint8_t *input_buffer,
                   uint8_t *output_buffer_length, uint8_t *output_buffer)
{
        *output_buffer_length = 1;
        output_buffer[0] = data++;
}
```

The first read will return 0x00, **the second read will return 0x00**, the third read will return 0x01. So the increment is lagging one transaction behind the actual data value.

I would expect the first read to return 0x00, and the second read to return 0x01.

Or to put it another way:

```
static uint8_t data = 0;

static void data_callback(uint8_t input_buffer_length, const uint8_t *input_buffer,
                   uint8_t *output_buffer_length, uint8_t *output_buffer)
{
        *output_buffer_length = 1;
        output_buffer[0] = 0x55;
}
```

The first read doesn't return 0x55, it returns 0x00. The second read returns 0x55.

If this is by design, what's the intended pattern for updating an internal value and returning it to the master on the next read? E.g. reading the current state of a pin.

**Comment by DavidAntliff** [comment]
I've spent quite a bit of time trying to understand how this is meant to work, and it's simply not clear to me what the original intent of the design is. For example, if I try to implement SMBus Read Byte protocol, then the data callback will be called once with a single byte of input (the command byte) but even if it loads the output buffer in that same transaction, this is not retrieved by the current I2C transaction but the subsequent one. This prevents implementation of SMBus Read Byte, and I have a similar problem with SMBus Write Byte for the same reason I think.

**Comment by DavidAntliff** [comment]
I see from an [external comment](http://www.avrfreaks.net/comment/841048#comment-841048) that the library only supports separate write/read transactions, so that if a write is required before a read (e.g. to set a register address within the slave device to subsequently read from) then the read operation must be performed as a separate second transaction.

**Comment by eriksl** [comment]
Yes, that is true. Sorry I didn't react sooner. This library is based on a scheme where the microcontroller is the I2C slave; it receives some bytes and sends some bytes in response. That's how I2C slaves work ;-) There is no provision for I2C master functionality. IIRC you can make the reply "null" if you don't want to send return anything. I must admit it has been quite a few years back that I made and used this code, so I'm not sure. A few years ago I moved on to ESP8266, which also doesn't have proper hardware I2C support, but at least it has a pile of RAM and CPU speed to make a proper implementation in software ;-)

**Comment by DavidAntliff** [comment]
Ah, thanks for responding. What I meant is that smbus-style "write-command/read result" transactions aren't supported - i.e. one can't write a command byte, and then, in the same transaction (by use of a restart signal) read back the result. Instead, the command must be written in one transaction, and then read back in a second, separate (i.e. a new start following a stop) transaction.

This hasn't been a problem for me but I was a bit confused at first as all the other I2C devices I've used until now supported smbus-style transactions. But now I understand how it works, I've been able to make good use of this code - thank you.

FWIW, I'm actually using a ATtiny84 via I2C as a slave to an ESP32 master, which I find to be a _lot_ more flexible and powerful than the ESP8266, although slightly more expensive.

**Comment by eriksl** [comment]
What do you mean with "restart signal"? Do you mean a "repeated start condition"? That's indeed not possible, it would mean the attiny doesn't have the time to prepare the answer, it also needs to act immediately on start conditions (which follows immediately).

But a start..stop..idle..start..stop isn't that different from a repeated start condition, the only real difference is when you have multiple masters on one bus, the "other" master could gain the bus inbetween.

Also the USI implementation has some "undocumented" features that make it less useful and really less versatile than a proper hardware I2C implemention, like the lack of a stop condition interrupt and the start condition handling not being 100% as documented.

I beg to differ regarding the ESP32 vs ESP8266. ESP32 is an ESP8266 with an extra core so the wireless stuff can run on one core (completely isolated from "user space") and the application running on the other. It also has bluetooth, OK can't work around that, but all of the other stuff can also be done on ESP8266. It's just a bit harder. And I like me challenge :-)

**Comment by woodz-** [comment]
> Yes, that is true. Sorry I didn't react sooner. This library is based on a scheme where the microcontroller is the I2C slave; it receives some bytes and sends some bytes in response. That's how I2C slaves work ;-) There is no provision for I2C master functionality. IIRC you can make the reply "null" if you don't want to send return anything. I must admit it has been quite a few years back that I made and used this code, so I'm not sure. A few years ago I moved on to ESP8266, which also doesn't have proper hardware I2C support, but at least it has a pile of RAM and CPU speed to make a proper implementation in software ;-)

So you moved to Arduino after all, despite mentioning you wouldn't do so in 2014?

**Comment by eriksl** [comment]
Wrong. I didn't Ardiuno then and I still don't like it.

I don't know where you get the idea from that you can use the ESP8266 only with Arduino.

I am using the NON-OS SDK and replaced any code there where possible, keeping as close to the hardware as possible.

**Comment by woodz-** [comment]
Was just a question. Good to hear you found another way to go. Would you mind to share it here a bit?
