### ISSUE TITLE
Readme callback signature legacy

### ISSUE THREAD

**Issue by mryellow** [eriksl/usitwislave#7]
Includes `uint8_t buffer_size` as first param unlike `attiny861_1` example. Looks like an older version of the functions signature.

https://github.com/eriksl/attiny861_1/blob/0d697a824d1f75efb8abd7f44d55167d7e249cb9/main.c#L280

**Comment by mryellow** [comment]
Notice this version is using the `buffer_size` param.

https://github.com/eriksl/attiny85_1/blob/b1b54107875a295c59ad495c069104ecfee810c1/twimain.c#L150

**Comment by eriksl** [comment]
Yes that is very well possible. Some code I have not been working on for a long time...
