### ISSUE TITLE
Query regarding setting up registers

### ISSUE THREAD

**Issue by bodgit** [eriksl/usitwislave#8]
I stumbled across your library as I'm looking to use an ATtiny [248]5 as an I2C slave and I was reading through the code to try and understand how it all works. One thing that has me doubting myself is where you're setting up some of the USI registers:

```
    USISR =
        (1      << USISIF)  |       // clear start condition flag
        (1      << USIOIF)  |       // clear overflow condition flag
        (0      << USIPF)   |       // !clear stop condition flag
        (1      << USIDC)   |       // clear arbitration error flag
        (0x00   << USICNT0);        // set counter to "8" bits
```

To my eyes there seems little reason to have `(0 << ...)` as the value will still be 0 no matter how much it gets shifted. Is this just a convention of documenting which flags aren't set and in fact I could just do `_BV(USISIF) | _BV(USIOIF) | _BV(USIDC)` instead and get the same final register value? I'm guessing the compiler will optimise the 0's away anyway but like I said the more I stare at it the more I wonder if there's something subtle I'm not getting w.r.t. ATtiny/ATmega as I've seen it in other peoples code as well.

**Comment by DavidAntliff** [comment]
It's just a way to keep the code tidier I think - think of it conceptually as shifting a zero into that place, even though as you say, it has no actual effect.

**Comment by eriksl** [comment]
Yes, exactly that. The compiler will eliminate all related code, so it will make no difference in the resulting code. It's a simple way to make features "toggles" you only need to replace 0 with 1 and v.v.
